version: "3"

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra_custom
    environment:
      MAX_HEAP_SIZE: 128M
      HEAP_NEWSIZE: 24M
      CASSANDRA_CLUSTER_NAME: docker cluster
      CASSANDRA_DC: docker
      CASSANDRA_SEEDS: cassandra
    ports:
      - 9042:9042
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.4.13
    container_name: zookeeper
    restart: unless-stopped

  kafka:
   image: wurstmeister/kafka:2.13-2.8.1
   container_name: kafka
   ports:
    -    "9092:9092"
   environment:
    KAFKA_ADVERTISED_HOST_NAME: localhost
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
   restart: unless-stopped
