cassandra:
  contact-points: localhost
  port: 9042
  keyspace-name: mykeyspace
  local-datacenter: datacenter1

spring.cloud.stream.bindings:
  produce-out-0:
    destination: person-topic
    contentType: application/json
  consume-in-0:
    destination: person-topic
    group: handsonapp
    contentType: application/json
    consumer:
      partitioned: true
      concurrency: 2
      autoRebalanceEnabled: true
      autoCommitOffset: true
      startOffset: earliest
      max-attempts: 3